### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Ntr0** [haproxytech/client-native#69]
client-native fails under certain conditions when handling multiple transactions by a consumer that uses the client in go routines (like dataplaneapi). 

Example Stacktrace:
```console
Jul 12 04:05:39 localhost env[42327]: fatal error: concurrent map writes
Jul 12 04:05:39 localhost env[42327]: goroutine 832915 [running]:
Jul 12 04:05:39 localhost env[42327]: runtime.throw(0x1bff306, 0x15)
Jul 12 04:05:39 localhost env[42327]:         runtime/panic.go:1116 +0x72 fp=0xc002653090 sp=0xc002653060 pc=0x4360f2
Jul 12 04:05:39 localhost env[42327]: runtime.mapassign_faststr(0x19e1b40, 0xc00108f260, 0xc00082d170, 0x24, 0x0)
Jul 12 04:05:39 localhost env[42327]:         runtime/map_faststr.go:291 +0x3d8 fp=0xc0026530f8 sp=0xc002653090 pc=0x414398
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/client-native/v2/configuration.(*Client).AddParser(0xc000fc4300, 0xc00082d170, 0x24, 0x0, 0x0)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/client-native/v2@v2.2.1-0.20210407113841-001437a6a3be/configuration/configuration.go:219 +0x30e fp=0xc002653188 sp=0xc0026530f8 pc=0xa523
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/client-native/v2/configuration.(*Transaction).startTransaction(0xc000fc4300, 0x2, 0xc00235f800, 0xc001ff4b90, 0xc0026532b8, 0xb8ac6a)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/client-native/v2@v2.2.1-0.20210407113841-001437a6a3be/configuration/transaction.go:115 +0x30d fp=0xc002653270 sp=0xc002653188 pc=0xaaf36d
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/client-native/v2/configuration.(*Transaction).StartTransaction(...)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/client-native/v2@v2.2.1-0.20210407113841-001437a6a3be/configuration/transaction.go:86
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/handlers.(*StartTransactionHandlerImpl).Handle(0xc000128430, 0xc0023b8900, 0x2, 0x1961be0, 0xc0021e0590, 0x0, 0x0)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/handlers/transaction.go:66 +0x46 fp=0xc0026532c8 sp=0xc002653270 pc=0x180dcc6
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/handlers.RateLimitedStartTransactionHandlerImpl.Handle(0x1f4dd00, 0xc001126010, 0x1f475a0, 0xc000128430, 0xc0023b8900, 0x2, 0x1961be
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/handlers/transaction.go:165 +0x12c fp=0xc002653320 sp=0xc0026532c8 pc=0x180ee8c
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/handlers.(*RateLimitedStartTransactionHandlerImpl).Handle(0xc001114080, 0xc0023b8900, 0x2, 0x1961be0, 0xc0021e0590, 0x0, 0x0)
Jul 12 04:05:39 localhost env[42327]:         <autogenerated>:1 +0x8a fp=0xc002653380 sp=0xc002653320 pc=0x181120a
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/operations/transactions.(*StartTransaction).ServeHTTP(0xc000fa43c0, 0x1f87bc0, 0xc00235f7e0, 0xc0023b8900)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/operations/transactions/start_transaction.go:86 +0x290 fp=0xc002653408 sp=0xc002653380 pc=0x17db430
Jul 12 04:05:39 localhost env[42327]: github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1f87bc0, 0xc00235f7e0, 0xc0023b8800)
Jul 12 04:05:39 localhost env[42327]:         github.com/go-openapi/runtime@v0.19.15/middleware/operation.go:28 +0x75 fp=0xc002653440 sp=0xc002653408 pc=0xb2ae35
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000fe0e80, 0x1f87bc0, 0xc00235f7e0, 0xc0023b8800)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653468 sp=0xc002653440 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/go-openapi/runtime@v0.19.15/middleware/router.go:77 +0x359 fp=0xc002653538 sp=0xc002653468 pc=0xb2b619
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000f46c40, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653560 sp=0xc002653538 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/go-openapi/runtime/middleware.Redoc.func1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/go-openapi/runtime@v0.19.15/middleware/redoc.go:72 +0x28e fp=0xc002653608 sp=0xc002653560 pc=0xb2b0ee
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc0011fc880, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653630 sp=0xc002653608 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/go-openapi/runtime/middleware.Spec.func1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/go-openapi/runtime@v0.19.15/middleware/spec.go:46 +0x190 fp=0xc0026536b8 sp=0xc002653630 pc=0xb2b7d0
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc0011fc8c0, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc0026536e0 sp=0xc0026536b8 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/adapters.RecoverMiddleware.func1.1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/adapters/adapters.go:152 +0x9d fp=0xc002653750 sp=0xc0026536e0 pc=0xbd257d
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000340480, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653778 sp=0xc002653750 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/rs/cors.(*Cors).Handler.func1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9 fp=0xc0026537d0 sp=0xc002653778 pc=0xbce179
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000f470e0, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc0026537f8 sp=0xc0026537d0 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/adapters.UniqueIDMiddleware.func1.1(0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/adapters/adapters.go:172 +0x1fb fp=0xc002653a18 sp=0xc0026537f8 pc=0xbd28bb
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000f47100, 0x1f87bc0, 0xc00235f7e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653a40 sp=0xc002653a18 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/haproxytech/dataplaneapi/adapters.LoggingMiddleware.func1.1(0x1f87c00, 0xc0018ce560, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/haproxytech/dataplaneapi/adapters/adapters.go:191 +0x155 fp=0xc002653ae0 sp=0xc002653a40 pc=0xbd2f15
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc000f47120, 0x1f87c00, 0xc0018ce560, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653b08 sp=0xc002653ae0 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: github.com/lestrrat-go/apache-logformat.(*ApacheLog).Wrap.func1(0x1f87fc0, 0xc0021267e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         github.com/lestrrat-go/apache-logformat@v0.0.0-20210106032603-24d066f940f8/logformat.go:65 +0x19f fp=0xc002653bc8 sp=0xc002653b08 pc=0xb8949f
Jul 12 04:05:39 localhost env[42327]: net/http.HandlerFunc.ServeHTTP(0xc0003404e0, 0x1f87fc0, 0xc0021267e0, 0xc000b03f00)
Jul 12 04:05:39 localhost env[42327]:         net/http/server.go:2042 +0x44 fp=0xc002653bf0 sp=0xc002653bc8 pc=0x7371c4
Jul 12 04:05:39 localhost env[42327]: net/http.serverHandler.ServeHTTP(0xc002127500, 0x1f87fc0, 0xc0021267e0, 0xc000b03f00)
```

This happens due to the fact that access to configuration.Client.parsers is not synchronized.

**Comment by amelhusic** [comment]
Hi @Ntr0 

Thanks for reporting the issue. With https://github.com/haproxytech/client-native/commit/f0e99da6a79ec207af808c28a779c0ecbce145ca commit this issue should be solved.

**Comment by Ntr0** [comment]
Great. Will there be a tagged release in the near future including this fix?

**Comment by Ntr0** [comment]
Also thank you :)

**Comment by amelhusic** [comment]
Hi @Ntr0 

You are welcome.
New tagged release [here](https://github.com/haproxytech/client-native/releases/tag/v2.4.2)

**Comment by Ntr0** [comment]
Hey @amelhusic : Thank you very much!
